#Generated by Fabric Compiler ( version 2019.1-patch2 <build 42169> ) at Mon Oct 12 17:14:32 2020

project -load "I:/example_ziguang/demo/08_1_hdmi_test/hdmi_test/synthesize/synplify_impl/../synplify_pro.prj"
open_file "I:/example_ziguang/demo/08_1_hdmi_test/hdmi_test/synthesize/synplify_impl/synplify.srs"
